apiVersion: v1
kind: Secret
metadata:
  name: ticket-booking-secrets
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  JWT_SECRET: "your-256-bit-secret-key-change-this-in-production-minimum-32-characters"
  REDIS_PASSWORD: ""
  STRIPE_API_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""

